### ISSUE TITLE
Credit conventions lists non-software conventions

### ISSUE THREAD

**Issue by ioistired** [creditstxt/credit-requirement#12]
I'm a bit confused as to why conventions.md lists conventions for works other than software. This is a software license exception after all.

**Comment by ioistired** [comment]
Maybe it's something of a "prior art" section like credits.txt has?

**Comment by kemitchell** [comment]
@bmintz if the software gets used to make a film, or an art piece, or bits of the code get listed in a book, don't the developers still deserve credit?

**Comment by kemitchell** [comment]
From current `master`:

> ## Conventions
> 
> Where widespread convention dictates a particular way to give credit for your kind of work, follow that convention.  For software provided in copies to run or install, give credit in documentation and notice files.  For software provided as a web service, give credits in `credits.txt`, according to <https://creditstxt.com>.

**Comment by ioistired** [comment]
I had a reason to reopen this but have since forgot.
