### ISSUE TITLE
“As an additional condition to the public license for this software”

### ISSUE THREAD

**Issue by tieguy** [creditstxt/credit-requirement#13]
Would be good somewhere to specify how this is to be indicated in the primary license, so that scanners can pick it up reliably.

**Comment by kemitchell** [comment]
Right you are. Just haven't got there yet.

The `README` should mention a roadmap that includes SPDX identification as an exception. That will enable `MIT WITH Credit-Requirement-1.0.0`.

I imagine the most straightforward way to apply the terms will be to simply append this text to the existing license text in `LICENSE`.

**Comment by ioistired** [comment]
I would rather do it in two files so that license detection tools (such as GitHub's) can pick up the primary license. There is precedent for this in the LGPL.

**Comment by kemitchell** [comment]
If GitHub and similar tools falsely present as, e.g., MIT, full stop, we have a problem.

**Comment by tieguy** [comment]
Right. There is no separate “primary license” here - this is no longer
MIT/BSD/etc. once this clause is applied.

**Comment by kemitchell** [comment]
@tieguy which begs the question of whether, optically, it's better to apply this "patch" to Blue Oak and announce as a freestanding permissive license.

**Comment by kemitchell** [comment]
@tieguy: Blue Oak + Credit Requirement = https://github.com/creditstxt/credit-license/blob/master/license.md

**Comment by ioistired** [comment]
Ah, my bad, GitHub doesn't display LGPLv3 or GPLv3 on an LGPLv3-licensed repo. It simply says "View license", and links to the LGPLv3 file. I also tested this with MIT + Credit Requirement [on a new repo](https://github.com/bmintz/credit-requirement-license-detection-test) following the same conventions as for the LGPLv3. Indeed it says "View License". So it seems like a new integrated license is unnecessary. It may be easier to apply but it may also cause confusion for those familiar with Blue Oak and not realizing this is basically just Blue Oak.

**Comment by kemitchell** [comment]
@tieguy, I foresee we'll take this out as two documents: a freestanding license, based on Blue Oak, and the same credit terms of that license, packaged as a general-purpose license exception.

I am going to close this issue and address it in the `README` for the license.
