### ISSUE TITLE
License Compatibility

### ISSUE THREAD

**Issue by ITR13** [creditstxt/credit-requirement#16]
Some licenses contain a clause not permitting [Modified and extended versions must be under the same license.](https://www.gnu.org/licenses/license-compatibility.en.html), I assume a license with this license as an addendum technically isn't the same license, so would this make them incompatible?

**Comment by kemitchell** [comment]
The fault for "compatibility" problems is GPL's.

The GPLs insist that their terms trump any other terms for code incorporated into a single project, without additional rules. FSF has fielded questions about credit requirements in licenses, but doesn't deem the issue worthy of enforcement via license terms.

Have a look at what GNU parallel does to request citation for the other's work.
