### ISSUE TITLE
Is X + Credit Requirement GPL compatible?

### ISSUE THREAD

**Issue by ioistired** [creditstxt/credit-requirement#17]
Can GPL software link against MIT + Credit Requirement, for instance?

**Comment by kemitchell** [comment]
Unlikely. See:

https://www.gnu.org/licenses/license-list.html#freetype

https://www.gnu.org/licenses/license-list.html#CPAL

**Comment by ioistired** [comment]
I gather from that that it would likely be compatible with the GPLv3, if I'm not mistaken. Though I don't comprehend the reasoning for CPAL.
