### ISSUE TITLE
Choose a distinctive name?

### ISSUE THREAD

**Issue by kemitchell** [creditstxt/credit-requirement#5]
"Credit Requirement" is 100% descriptive of what the legal text tries to do, and therefore not protectable as a trademark, or particularly fun.

Perhaps we could think of a memorable and suggestive name for the project?

**Comment by ioistired** [comment]
What are the advantages of trademarking the name?

**Comment by kemitchell** [comment]
If someone else tries to publish an alternative or changed form with the same name, I could use the trademark to stop them. It may also help to secure names on various platforms that assign organization handles, like GitHub.

**Comment by ioistired** [comment]
Hmm… I don't have any solid name ideas yet, but here's some brainstorming:
Blue Oak came out of Oakland, where the project started. This project started online. Maybe something related to that? Especially since the project itself also relates to network use. Ah, that leads me to [X-Clacks-Overhead](https://xclacksoverhead.org/). The Clacks continue to carry Terry Pratchet's name through the wired. How does "Clacks Exception" sound? A little weird, but I could get used to it.

**Comment by ioistired** [comment]
Actually I really like the symbolism of X-Clacks-Overhead since its mission statement is "A man is not dead while his name is still spoken." :smiley:

**Comment by kemitchell** [comment]
That's definitely the gist of the tool! But I'm afraid deep Pratchett refs are a bit niche. I'd prefer to go with something that nearly everyone understands intuitively, rather than something that makes them search Google. ;-P

**Comment by ioistired** [comment]
Aww ok :(

**Comment by kemitchell** [comment]
Put the quote in README?

**Comment by ioistired** [comment]
> If someone else tries to publish an alternative or changed form with the same name, I could use the trademark to stop them.

Wouldn't that be handled by a DMCA letter due to the license in the README file?

> It may also help to secure names on various platforms that assign organization handles, like GitHub.

Well this wouldn't be handled by the license, so that's fair.

**Comment by kemitchell** [comment]
If Bob writes _an entirely new legal text_, without starting from mine, and calls it "Credit Requirement", why does he have to follow my license rules?

**Comment by ioistired** [comment]
> Put the quote in README?

I'd like to try and change it to use gender-neutral language if possible. It *is* a quote though.

**Comment by kemitchell** [comment]
> > Your aren't dead while your name is still spoken.
> 
> After [Sir Terry Pratchett](https://en.wikipedia.org/wiki/Going_Postal)

**Comment by ioistired** [comment]
> That's definitely the gist of the tool! But I'm afraid deep Pratchett refs are a bit niche. I'd prefer to go with something that nearly everyone understands intuitively, rather than something that makes them search Google. ;-P

See, and here I was thinking of using a Lain reference :P

**Comment by ioistired** [comment]
@sayaks got any ideas?

**Comment by ioistired** [comment]
What if we tried translating "attribution", "credit", "honor", "trust", etc into other languages? I tried in Spanish with "attribution" and "credit" but just got words that sound like English :/.

**Comment by ioistired** [comment]
My friend came up with "DevCred" which I think sounds too hip, sounds unrefined to me. "Credi" sounds neat but maybe a bit too cutesy? "Cover Charge" perhaps, to somewhat relate back to mechanical royalties, or maybe something else related to royalties, if it's possible to do so without implying commercial aspects. Or something about norms, perhaps. "Credical"? Or maybe something relating to signatures, like on artwork.

**Comment by ioistired** [comment]
Credi is starting to grow on me btw :P

**Comment by lilizoey** [comment]
How about something like, heritage, lineage, kinship, or similar? 
Referring to how names of families or places and so on could live for several generations.

**Comment by kemitchell** [comment]
@sayaks, welcome!

I really appreciate the name suggestions. More than I've been able to come up with on my own! But I'm starting to think plain-Jane descriptive may just be the way to go. I'm coming up with any names that do as much to convey what the text _does_, and I think that's the most important thing the name can do.

**Comment by ioistired** [comment]
Is it worth it to forgo trademarking?

**Comment by kemitchell** [comment]
I do plan to trademark a name of some kind, to protect the integrity of the terms that I release. But I think it best to set this issue aside for now.

I suspect it may be easier, and more important, to come up with a distinctive name for a complete license. I could easily see announcing both a permissive license with credit terms, as well as the credit terms alone, for use as an addition to other licenses.
